insert into "public"."topics" (content, is_active) values
('navigating friendships in your twenties', true),
('the revival of vintage digital cameras', true),
('hustle culture vs quiet quitting', true),
('my hottest take on a popular movie', true),
('the most overrated coffee shop aesthetic', true),
('documenting life vs living in the moment', true),
('the difference between style and fashion', true),
('my concept of an ideal weekend routine', true),
('analyzing celebrity street style', true),
('thrift store shopping strategies', true),
('podcast recommendations that actually changed my life', true),
('the pressure to monetize your hobbies', true),
('how social media alters our attention spans', true),
('nostalgic trends I hope never come back', true),
('what my Spotify Wrapped says about my personality', true),
('the ethics of AI generated art and writing', true),
('a habit I am intentionally trying to build', true),
('rating different generations'' slang words', true),
('my approach to setting personal boundaries', true),
('the reality of digital nomad lifestyle', true);
